<a href="https://colab.research.google.com/github/gulliyevn/MachineLearningProjects/blob/main/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
titanic=pd.read_csv('/content/drive/MyDrive/Titanic-Dataset.csv')

In [3]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

# passenger ticket cabin

In [4]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
titanic.drop(['PassengerId', 'Ticket', 'Cabin','Name'],axis=1,inplace=True)

In [6]:
titanic.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
titanic.shape

(891, 8)

In [8]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [9]:
titanic.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [12]:
X=titanic.drop('Survived',axis=1)
y=titanic['Survived'].copy()

In [13]:
X

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [14]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
from sklearn.ensemble import RandomForestClassifier
reg=RandomForestClassifier()

In [16]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
txt=X_train.select_dtypes(exclude=[np.number]).columns
num=X_train.select_dtypes(include=[np.number]).columns

In [20]:
txtpip=Pipeline([('impute',SimpleImputer(strategy='constant',fill_value='frequent')),
                 ('onehot',OneHotEncoder())])
numpip=Pipeline([('impute',SimpleImputer(strategy='median'))])

In [21]:
transformer=ColumnTransformer([('onehot',txtpip,txt),
             ('numpip',numpip,num)],
             remainder='passthrough')

In [22]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [23]:
titanic.columns.tolist()

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [25]:
Xtt=transformer.fit_transform(X_train)
tc=transformer.get_feature_names_out()
Xttdf=pd.DataFrame(Xtt,columns=tc)

In [26]:
Xtst=transformer.transform(X_test)
tc=transformer.get_feature_names_out()
Xtstdf=pd.DataFrame(Xtst,columns=tc)

In [27]:
reg.fit(Xttdf,y_train)

RandomForestClassifier()

In [28]:
reg.score(Xtstdf,y_test)

0.8268156424581006

In [29]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
full_pipeline1 = Pipeline([
('preprocessing', transformer),
('random_forest', model)])

full_pipeline1.fit(X_train, y_train)

preds1=full_pipeline1.predict(X_test)

preds1

array([ 1.43180406e-01,  6.01523313e-01,  1.45938454e-01,  2.75360141e-02,
        6.52178861e-01,  8.72568586e-01,  7.23723651e-01,  8.14855760e-01,
        5.35317469e-01,  3.02695086e-01,  1.05829620e+00,  5.37084768e-01,
        1.07179731e+00,  1.11706128e-01,  1.48380184e-01,  9.89012692e-02,
       -2.17424347e-02,  1.64979196e-01,  7.99786953e-01,  2.98662452e-01,
        2.94375709e-01, -2.62618755e-03,  1.02404825e+00,  8.64990503e-01,
        6.96625720e-01,  9.98589927e-02,  3.92289643e-02,  1.44531136e-01,
        1.10077556e+00,  9.81916798e-01,  6.07784946e-02,  1.05397776e+00,
        1.36704183e-01,  5.35227508e-01,  2.03261760e-01,  1.18694770e-01,
        1.11464422e-01,  1.99889193e-01,  9.88101460e-02,  9.88101460e-02,
        7.05062947e-01,  1.09567165e+00,  9.99523985e-03,  6.22346654e-01,
        1.50581796e-01, -1.92806760e-01,  9.45172323e-01,  9.10183674e-01,
       -4.15702873e-03,  1.36803979e-01,  7.80454880e-01,  1.45940314e-01,
        4.85606944e-01,  

In [30]:
full_pipeline1.score(X_test, y_test)

0.41044954026305636

In [ ]:
#Add more hyperparameters=ParamGrid

In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

param_grid={
    'n_estimators':[50,60],
    'max_depth':[10,15,30]

}

grid_search=GridSearchCV(estimator=model,param_grid=param_grid,cv=3)
grid_search.fit(Xttdf,y_train)

GridSearchCV(cv=3, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [10, 15, 30], 'n_estimators': [50, 60]})

In [35]:
grid_search.score(Xtstdf,y_test)

0.27494580806579905

In [36]:
grid_search.best_score_

0.3861664320314661

In [37]:
grid_search.best_estimator_

RandomForestRegressor(max_depth=10, n_estimators=60)

In [38]:
grid_search.best_params_

{'max_depth': 10, 'n_estimators': 60}

In [39]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()

param_grid ={
    'max_depth':[10,15,30],
    'max_features':['sqrt','log2'],
    'splitter':['best','random']
}

tree=DecisionTreeRegressor()
rig=GridSearchCV(tree,param_grid=param_grid)
rig.fit(Xttdf,y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [10, 15, 30],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']})

In [40]:
rig.best_params_

{'max_depth': 10, 'max_features': 'log2', 'splitter': 'best'}

In [41]:
rig.score(Xtstdf,y_test)

0.190848738954705

In [42]:
rig.best_estimator_.score(Xtstdf,y_test)

0.190848738954705

In [43]:
from sklearn.dummy import DummyClassifier

dummy_clf=DummyClassifier()
dummy_clf.fit(X_train,y_train)
print(any(dummy_clf.predict(X_train)))

False


In [44]:
cross_val_score(dummy_clf,X_train,y_train,cv=3)

array([0.6092437 , 0.60759494, 0.61181435])

In [45]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score

sgd_clf= SGDClassifier(random_state=42)
sgd_clf.fit(Xttdf,y_train)

SGDClassifier(random_state=42)

In [46]:
cross_val_score(sgd_clf, Xtstdf, y_test, cv=3)

array([0.65      , 0.63333333, 0.49152542])

In [47]:
from sklearn.model_selection import cross_val_predict

y_train_pred=cross_val_predict(sgd_clf,Xttdf,y_train,cv=3)
y_train_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,

In [48]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_train,y_train_pred)

0.654054054054054

In [49]:
recall_score(y_train,y_train_pred)

0.4352517985611511

In [50]:
from sklearn.metrics import f1_score
f1_score(y_train,y_train_pred)

0.5226781857451404