<a href="https://colab.research.google.com/github/gulliyevn/MachineLearningProjects/blob/main/TitanicUpdate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
titanic=pd.read_csv('/content/drive/MyDrive/Titanic-Dataset.csv')

In [3]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [4]:
titanic.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
titanic.drop(['PassengerId', 'Ticket', 'Cabin','Name'],axis=1,inplace=True)

In [6]:
titanic.describe()

Survived      Pclass         Age       SibSp       Parch        Fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [7]:
titanic.shape

(891, 8)

In [8]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [9]:
titanic.isna().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [10]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [12]:
X=titanic.drop('Survived',axis=1)
y=titanic['Survived'].copy()

In [13]:
X

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [14]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [15]:
from sklearn.ensemble import RandomForestClassifier
reg=RandomForestClassifier()

In [16]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [17]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
text=X_train.select_dtypes(exclude=[np.number]).columns
num=X_train.select_dtypes(include=[np.number]).columns

In [20]:
text_pipline=Pipeline([('impute',SimpleImputer(strategy='constant',fill_value='frequent')),
                 ('onehot',OneHotEncoder())])
num_pipline=Pipeline([('impute',SimpleImputer(strategy='median'))])

In [21]:
transformer=ColumnTransformer([('onehot',text_pipline,text),
             ('num_pipline',num_pipline,num)],
             remainder='passthrough')

In [22]:
titanic

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [23]:
titanic.columns.tolist()

['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']

In [24]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((712, 7), (179, 7), (712,), (179,))

In [25]:
X_train_transform=transformer.fit_transform(X_train)
transformer_column=transformer.get_feature_names_out()
X_train_transform_df=pd.DataFrame(X_train_transform,columns=transformer_column)

In [26]:
X_test_transform=transformer.transform(X_test)
transformer_column=transformer.get_feature_names_out()
X_test_transform_df=pd.DataFrame(X_test_transform,columns=transformer_column)

In [27]:
reg.fit(X_train_transform_df,y_train)

RandomForestClassifier()

In [28]:
reg.score(X_test_transform_df,y_test)

0.8156424581005587

In [29]:

model=RandomForestClassifier()
full_pipeline2 = Pipeline([
('preprocessing', transformer),
('random_forest', model)])

full_pipeline2.fit(X_train, y_train)

preds2=full_pipeline2.predict(X_test)

preds2

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0])

In [30]:
np.random.seed(42)
cross_val_score(full_pipeline2,X,y,cv=8)

array([0.76785714, 0.75892857, 0.80357143, 0.85585586, 0.85585586,
       0.78378378, 0.79279279, 0.87387387])

In [31]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
full_pipeline1 = Pipeline([
('preprocessing', transformer),
('random_forest', model)])

full_pipeline1.fit(X_train, y_train)

preds1=full_pipeline1.predict(X_test)

preds1

array([ 0.14854316,  0.20577647,  0.58706828,  0.64551157,  0.68942724,
        0.10244219,  0.82763792,  0.83952324,  0.34001094,  0.11568882,
        0.72527442,  0.30701242,  1.00190025,  1.06762375,  0.74152085,
        0.23111196,  0.54056699,  0.54148071,  0.15066132,  0.09721648,
        0.71918247,  0.70373459,  0.18245662,  0.78479634,  0.19852402,
        0.83576565,  0.79727939,  0.44939439,  0.4954927 ,  0.10355024,
        0.23710884,  0.11627693,  0.09078545, -0.03681383,  0.10405625,
        0.9740203 ,  0.6454958 ,  0.55833579,  0.22434404,  0.11631503,
        0.45172855,  0.17509162,  1.01656287,  0.27221201,  0.10060088,
        0.03105364,  0.10035904,  0.14181307,  0.0320836 ,  0.07802987,
        0.59838866,  0.07802987,  0.64338158,  0.13896824,  0.82243261,
        0.15459629,  0.39005792,  0.34843221,  0.14827565,  0.33875403,
        0.30701242,  0.03584789,  0.30652662,  0.02104964,  0.77024164,
        0.6942826 ,  0.71105752,  0.10035904,  0.6816126 ,  0.09

In [32]:
full_pipeline1.score(X_test, y_test)

0.4326471923036791

In [33]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

param_grid={
    'n_estimators':[50,60],
    'max_depth':[10,15,30]

}

grid_search=GridSearchCV(estimator=model,param_grid=param_grid,cv=3)
grid_search.fit(X_train_transform_df,y_train)

GridSearchCV(cv=3, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [10, 15, 30], 'n_estimators': [50, 60]})

In [34]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostClassifier
from sklearn.svm import SVC

rfc = RandomForestClassifier()
abc = AdaBoostClassifier()
svc = SVC()
reg= RandomForestRegressor()

model_pipeline = Pipeline([('model', rfc)])

rfc_param = {'model__max_depth': [6],
             'model__max_features': ['log2'],
             'model': [rfc]}
reg_param={  'model__max_depth': [2,3],
             'model': [reg]}
abc_param = {'model__n_estimators': [10],
             'model': [abc]}

params = [rfc_param, abc_param,reg_param]

grid = GridSearchCV(model_pipeline, params, cv=3)

grid.fit(X_train_transform_df,y_train)

GridSearchCV(cv=3,
             estimator=Pipeline(steps=[('model',
                                        RandomForestClassifier(max_depth=6,
                                                               max_features='log2'))]),
             param_grid=[{'model': [RandomForestClassifier(max_depth=6,
                                                           max_features='log2')],
                          'model__max_depth': [6],
                          'model__max_features': ['log2']},
                         {'model': [AdaBoostClassifier()],
                          'model__n_estimators': [10]},
                         {'model': [RandomForestRegressor()],
                          'model__max_depth': [2, 3]}])

In [55]:
grid.score(X_test_transform_df,y_test)

0.8379888268156425

In [36]:
grid.best_score_

0.8132113604935646

In [37]:
grid.best_estimator_

Pipeline(steps=[('model',
                 RandomForestClassifier(max_depth=6, max_features='log2'))])

In [38]:
grid.best_params_

{'model': RandomForestClassifier(max_depth=6, max_features='log2'),
 'model__max_depth': 6,
 'model__max_features': 'log2'}

In [39]:
grid_search.score(X_test_transform_df,y_test)

0.5162496073451508

In [40]:
grid_search.best_score_

0.35829081905213034

In [41]:
grid_search.best_estimator_

RandomForestRegressor(max_depth=10, n_estimators=50)

In [42]:
grid_search.best_params_

{'max_depth': 10, 'n_estimators': 50}

In [43]:
from sklearn.tree import DecisionTreeRegressor
model=DecisionTreeRegressor()

param_grid ={
    'max_depth':[10,15,30],
    'max_features':['sqrt','log2'],
    'splitter':['best','random']
}

tree=DecisionTreeRegressor()
rig=GridSearchCV(tree,param_grid=param_grid)
rig.fit(X_train_transform_df,y_train)

GridSearchCV(estimator=DecisionTreeRegressor(),
             param_grid={'max_depth': [10, 15, 30],
                         'max_features': ['sqrt', 'log2'],
                         'splitter': ['best', 'random']})

In [44]:
rig.best_params_

{'max_depth': 10, 'max_features': 'sqrt', 'splitter': 'random'}

In [45]:
rig.score(X_test_transform_df,y_test)

0.35449395736760525

In [46]:
rig.best_estimator_.score(X_test_transform_df,y_test)

0.35449395736760525

In [47]:
from sklearn.dummy import DummyClassifier

dummy_clf=DummyClassifier()
dummy_clf.fit(X_train,y_train)
print(any(dummy_clf.predict(X_train)))

False


In [48]:
cross_val_score(dummy_clf,X_train,y_train,cv=3)

array([0.61344538, 0.61181435, 0.61181435])

In [49]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score

sgd_clf= SGDClassifier(random_state=42)
sgd_clf.fit(X_train_transform_df,y_train)

SGDClassifier(random_state=42)

In [50]:
cross_val_score(sgd_clf, X_test_transform_df, y_test, cv=3)

array([0.36666667, 0.63333333, 0.62711864])

In [51]:
from sklearn.model_selection import cross_val_predict

y_train_pred=cross_val_predict(sgd_clf,X_train_transform_df,y_train,cv=3)
y_train_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [52]:
from sklearn.metrics import precision_score, recall_score

precision_score(y_train,y_train_pred)

0.48498845265588914

In [53]:
recall_score(y_train,y_train_pred)

0.7608695652173914

In [54]:
from sklearn.metrics import f1_score
f1_score(y_train,y_train_pred)

0.5923836389280677